import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import preact from '@preact/preset-vite';
import { defineConfig, type ServerOptions } from 'vite';

// Fourth build target (alongside the extension's app / content / webmcp passes):
// the Word task-pane add-in. It imports the portable core from ../src directly.
//
// Office requires the task pane to be served over HTTPS. We load the localhost
// certificate generated by `npx office-addin-dev-certs install`; if it isn't
// installed yet (or for `addin:build`, which doesn't need it) we fall back to
// HTTP so the build/plain-browser dev still works.
const here = dirname(fileURLToPath(import.meta.url));

export default defineConfig(async () => {
  let https: ServerOptions['https'];
  try {
    const { getHttpsServerOptions } = await import('office-addin-dev-certs');
    const opts = await getHttpsServerOptions();
    https = { key: opts.key, cert: opts.cert, ca: opts.ca };
  } catch {
    // Certs not installed yet — run `npx office-addin-dev-certs install`.
  }

  return {
    root: here,
    plugins: [preact()],
    build: {
      outDir: 'dist',
      emptyOutDir: true,
      rollupOptions: { input: resolve(here, 'taskpane.html') },
    },
    server: { port: 3000, strictPort: true, https },
  };
});
