import { useEffect, useState } from 'preact/hooks';
import type { ProductMeta } from '../shared/messages';
import { saveFile } from '../sidebar/download';

function fmt(iso: string): string {
  return new Date(iso).toLocaleString();
}

function fmtSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function base64ToBlob(base64: string, mimeType: string): Blob {
  const bin = atob(base64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new Blob([bytes], { type: mimeType });
}

/**
 * Files scheduled tasks and event triggers generate (e.g. a PowerPoint from a
 * "check this site every morning" job) land here durably in OPFS — see
 * `productStore.ts` — instead of only ever firing an OS download prompt for
 * every unattended run, or a click-to-download card no sidebar was open to see.
 */
export function ProductsPage() {
  const [products, setProducts] = useState<ProductMeta[]>([]);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const reload = () => {
    chrome.runtime.sendMessage({ type: 'products_list' }).then((r: ProductMeta[]) => setProducts(Array.isArray(r) ? r : []));
  };

  useEffect(reload, []);

  const download = async (p: ProductMeta) => {
    setError(null);
    setBusyId(p.id);
    try {
      const res = (await chrome.runtime.sendMessage({ type: 'product_get', id: p.id })) as { meta: ProductMeta; dataBase64: string } | null;
      if (!res) {
        setError(`Could not load "${p.filename}" — it may have been removed.`);
        return;
      }
      saveFile(base64ToBlob(res.dataBase64, res.meta.mimeType), res.meta.filename);
    } finally {
      setBusyId(null);
    }
  };

  const remove = async (id: string) => {
    setBusyId(id);
    try {
      await chrome.runtime.sendMessage({ type: 'product_delete', id });
      reload();
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div class="ws-products-page">
      <h2>Products</h2>
      <p class="settings-note">
        Files generated by scheduled tasks and event triggers (e.g. a PowerPoint or Word doc from an
        unattended run) — saved here on-device rather than forced into an OS download for every job.
        Download or delete them any time; nothing here expires on its own.
      </p>
      {error && <div class="banner banner-error">{error}</div>}
      {products.length === 0 ? (
        <p class="settings-note">
          Nothing yet — a file generated during a scheduled task or event trigger run will appear here.
        </p>
      ) : (
        <ul class="sites-list ws-run-list">
          {products.map((p) => (
            <li key={p.id} class="ws-run-item">
              <div class="ws-run-header">
                <span class="site-name">{p.filename}</span>
                <span class="site-desc">
                  {fmt(p.createdAt)} · {fmtSize(p.sizeBytes)}
                  {p.sourceTitle ? ` · from "${p.sourceTitle}"` : ''}
                </span>
                <button class="btn btn-small" disabled={busyId === p.id} onClick={() => download(p)}>Download</button>
                <button class="icon-btn" title="Delete" disabled={busyId === p.id} onClick={() => remove(p.id)}>✕</button>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
